language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

matrix:
    allow_failures:
        - perl: "5.10"
    fast_finish: true

before_install:
    - cpanm --notest --force Pod::Readme

install:
    - cpanm --quiet --notest --skip-satisfied Dist::Milla
    - cpanm --installdeps .

# full release test
script:
    - milla smoke --release --author

# normal tests and report test coverage to coveralls.io
after_success:
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
    - perl Build.PL && ./Build build && cover -test -report coveralls
